[build.environment]

#REACT_APP_AGORA_APP_ID="58dc40def494479386068478bad00114"
#REACT_APP_AGORA_LOG=true
#ELECTRON_START_URL="http://localhost:3000"
#REACT_APP_AGORA_CUSTOMER_ID="89c8f129b92d471d8b2c247bcb9eaf2c"
#REACT_APP_AGORA_CUSTOMER_CERTIFICATE="15020b38750b48fe9b5ed5ba9683fd31"
#REACT_APP_AGORA_RESTFULL_TOKEN="ZTNhMDA2NjQ4YjY4NDY1ZTlhM2EwYTVkZjU0NjA3NTQ6OGQ0NWY0YmY5YmMzNDQ0OThlMmYxYjMyMTdjNWIwZmI="
#REACT_APP_BUILD_VERSION="0.0.1"
#REACT_APP_AGORA_APP_SDK_DOMAIN="https://api.agora.io"
#REACT_APP_AGORA_APP_SDK_LOG_SECRET="agora_edu_sdk_log_secret"

#REACT_APP_NETLESS_APP_ID="4HT8YPhAEeqmMKnrv2l9Ug/cl3sx6G1-RLk9Q"

#REACT_APP_YOUR_BACKEND_WHITEBOARD_API="https://api.agora.io/edu/v1/apps/%app_id%/room/%room_id%/board"

#REACT_APP_YOUR_OWN_OSS_BUCKET_NAME="steplive'
#REACT_APP_YOUR_OWN_OSS_BUCKET_FOLDER="recordings"
#REACT_APP_YOUR_OWN_OSS_BUCKET_REGION="ap-south-1"
#REACT_APP_YOUR_OWN_OSS_BUCKET_KEY="LTAI4GEppxbpTqoub7apsFni"
#REACT_APP_YOUR_OWN_OSS_BUCKET_SECRET="1UXHLcSXaczmU7JOIG3DpZKLXR7zaE"
#REACT_APP_YOUR_OWN_OSS_CDN_ACCELERATE="oss-ap-south-1.aliyuncs.com"