parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''

jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-10.13'

    variables:
      - group: AgoraKeys

    steps:
      - script: cd ${{ parameters.workingDirectory }} && ls && python ci.env.py
        env:
          AGORA_APP_ID: $(agora.appID)
          WHITE_BOARD_TOKEN: $(agora.whiteBoardToken)

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'TestCertificates2019.p12'
          certPwd: $(agora.passWord)
          
      - task: InstallAppleProvisioningProfile@1
        inputs:
          provProfileSecureFile:
              'AgoraIOTest2019.mobileprovision'
      
      - script: cd ${{ parameters.workingDirectory }} && chmod +x build.sh && ./build.sh

      - script: cd ${{ parameters.workingDirectory }} && mkdir app && mv AgoraEducationQA.ipa app && mv AgoraEducationQA.xcarchive app

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/app
          ArtifactName: ${{ parameters.displayName }}

      - template: github-release.yml
        parameters:
          displayName: ${{ parameters.displayName }}

